{% set name = "lofo-importance" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 69562adf56d401a53d48c8210d0fcd68de6e04f4af37d7c2b0c75578f46313be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lightgbm
    - networkx
    - numpy >=1.17.3
    - pandas
    - scikit-learn >=0.20.3
    - scipy
    - tqdm

test:
  imports:
    - lofo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aerdem4/lofo-importance
  summary: Leave One Feature Out Importance
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/aerdem4/lofo-importance
  doc_url: https://github.com/aerdem4/lofo-importance/blob/master/README.md

extra:
  recipe-maintainers:
    - melonhead901
