{% set name = "lofo-importance" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lofo-importance-{{ version }}.tar.gz
  sha256: 1803f6c5eff4f32732360496340b1f2c6f1c6d26bad4e8c110faef02d9746555

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - lightgbm
    - networkx
    - numpy >=1.17.3
    - pandas
    - scikit-learn >=0.20.3
    - scipy
    - tqdm

test:
  imports:
    - lofo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aerdem4/lofo-importance
  summary: Leave One Feature Out Importance
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/aerdem4/lofo-importance
  doc_url: https://github.com/aerdem4/lofo-importance/blob/master/README.md

extra:
  recipe-maintainers:
    - melonhead901
