{% set name = "lofo-importance" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lofo-importance-{{ version }}.tar.gz
  sha256: 6d0a631f6d8ad74fa4b1b36e119d9681ebcce5b4ccae4744e497f7894e0d6420

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lightgbm
    - networkx
    - numpy >=1.17.3
    - pandas
    - scikit-learn >=0.20.3
    - scipy
    - tqdm

test:
  imports:
    - lofo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aerdem4/lofo-importance
  summary: Leave One Feature Out Importance
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/aerdem4/lofo-importance
  doc_url: https://github.com/aerdem4/lofo-importance/blob/master/README.md

extra:
  recipe-maintainers:
    - melonhead901
